dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest-cov codecov
script: pytest --cov=./
after_success:
  - codecov --token=$CODECOV_TOKEN
